### ISSUE TITLE
HookMain.java里，571行后的逻辑是还没有完成的吗

### ISSUE THREAD

**Issue by gimlyon** [w2016561536/android_virtual_cam#11]
![hookMain571](https://user-images.githubusercontent.com/20081668/131454451-d06ac207-c541-4679-b2b1-33bcf0303b4b.PNG)

**Comment by w2016561536** [comment]
那个是之前用于软解的代码，开了一个线程，循环读取文件，但是现在用了mediacodec硬解码，就废弃了。

**Comment by gimlyon** [comment]
百度健康里的人脸识别，没有显示virtual.mp4的内容。
<img src="https://user-images.githubusercontent.com/20081668/131457996-79b77c10-3127-4142-a412-b378ff7fc8ee.jpg" width = "300" alt="Screenshot_20210831-114103" align="center" />
日志如下：

> Loading module com.example.vcam from /data/app/com.example.vcam-3bv9Q2RLzljh3xN23TaX8w==/base.apk
  Loading class com.example.vcam.HookMain
Loading module com.example.vcam from /data/app/com.example.vcam-3bv9Q2RLzljh3xN23TaX8w==/base.apk
  Loading class com.example.vcam.HookMain
帧预览回调初始化：宽：640 高：480 帧率：30

virtual.mp4的视频信息应该是对的。
<img src="https://user-images.githubusercontent.com/20081668/131459673-66b16601-3040-47d3-b694-0a738c82f15d.PNG" width = "300" alt="virtual视频信息" align="center" />

**Comment by w2016561536** [comment]
> 百度健康里的人脸识别，没有显示virtual.mp4的内容。
> 
> <img src="https://user-images.githubusercontent.com/20081668/131457996-79b77c10-3127-4142-a412-b378ff7fc8ee.jpg" width = "300" alt="Screenshot_20210831-114103" align="center" />
> 
> 日志如下：
> 
> 
> 
> > Loading module com.example.vcam from /data/app/com.example.vcam-3bv9Q2RLzljh3xN23TaX8w==/base.apk
> 
>   Loading class com.example.vcam.HookMain
> 
> Loading module com.example.vcam from /data/app/com.example.vcam-3bv9Q2RLzljh3xN23TaX8w==/base.apk
> 
>   Loading class com.example.vcam.HookMain
> 
> 帧预览回调初始化：宽：640 高：480 帧率：30
> 
> 
> 
> virtual.mp4的视频信息应该是对的。
> 
> <img src="https://user-images.githubusercontent.com/20081668/131459673-66b16601-3040-47d3-b694-0a738c82f15d.PNG" width = "300" alt="virtual视频信息" align="center" />
> 
> 
> 
> 

1、授予应用存储读取权限（目标应用）
2、更新到最新release重启手机
3、检查视频路径是否正确

**Comment by gimlyon** [comment]
感谢作者解答，是读取权限的问题。现在又有一个问题，app是在获取virtual.mp4的内容了，但显示的却是摄像头的内容。我尝试了多种拍摄距离，甚至拍摄了一个从近到远的脸部视频，可是一直提示识别的脸不在框内。
<img src="https://user-images.githubusercontent.com/20081668/131469114-1bdf331b-c84c-47fb-8ea8-07863eea3acf.jpg" width = "300" alt="Screenshot_20210831-162214" align="center" />

**Comment by gimlyon** [comment]
我试着把视频左旋90°，识别成功了！

**Comment by w2016561536** [comment]
> 我试着把视频左旋90°，识别成功了！

你是不是把宽高弄反了
