### ISSUE TITLE
如果直接选择照片就好了

### ISSUE THREAD

**Issue by 0only** [w2016561536/android_virtual_cam#14]
首先感谢大佬的模块
拍照后能直接去选择照片就好了
还有就是有1000.bmp在的情况下,创建disable.jpg,还是hook相机,是钉钉

**Comment by w2016561536** [comment]
> 首先感谢大佬的模块
> 
> 拍照后能直接去选择照片就好了
> 
> 还有就是有1000.bmp在的情况下,创建disable.jpg,还是hook相机,是钉钉
> 
> 

钉钉用的是camera接口
其实我也想去选择文件
但是我没有时间深究content provider，就偷了个懒

**Comment by w2016561536** [comment]
而且把路径强制定于DCIM，能规避安卓11的很多权限问题

**Comment by 0only** [comment]
谢谢,
期望做得更好
