### ISSUE TITLE
在Android12中一些问题

### ISSUE THREAD

**Issue by SummonHIM** [w2016561536/android_virtual_cam#140]
- 过长的Toast在安卓12中都被隐藏了，详细信息都看不了
- 工作账户使用的是 /storage/emulated/10/DCIM/Camera1/而本模块仅检测/storage/emulated/0/DCIM/Camera1/目录

**Comment by kenlam5551** [comment]
可以在log看到 你能用到1000.bmp嗎?

**Comment by SummonHIM** [comment]
> 可以在log看到 你能用到1000.bmp嗎?

我把他的toast全改成log编译了一个就行了

暂时没用图片 还不知道

**Comment by kenlam5551** [comment]
可以幫忙試一試用1000.bmp 難得見到活人在這裡 我可以播出視頻 但圖片放不到 用的手機是三星 s20 s9+ 也有

**Comment by kenlam5551** [comment]
或大佬能不能留個tg或wechat一起研究
我wechat是 Samgorken
tg是 exiadynams
