### ISSUE TITLE
I fixed the problem

### ISSUE THREAD

**Issue by joefrazier498** [w2016561536/android_virtual_cam#144]
somebody found a solution ?

**Comment by kenlam5551** [comment]
Hi, i have emailed to u bro, can u add my telegram?
@exiadynams

**Comment by kenlam5551** [comment]
Bro here?

**Comment by joefrazier498** [comment]
Hello, add me on telegram : KATARAKT

    Le dimanche 1 janvier 2023 à 09:34:18 UTC+1, kenlam5551 ***@***.***> a écrit :  
 
 


Bro here?

**Comment by westruk** [comment]
SCAM! Refuses to work through escrow! Also cannot provide video evidence that the module is working.

**Comment by joefrazier498** [comment]
it works
