### ISSUE TITLE
Virtual camera not using specified image from /Camera1/ folder when taking photo

### ISSUE THREAD

**Issue by testesneps** [w2016561536/android_virtual_cam#149]
The virtual camera(video) is working properly, but when I try to take a photo, it simply takes a regular picture using my default camera instead of using the image I placed under the /[INTERNAL_STORAGE]/DCIM/Camera1/ folder. I followed the guide's instructions and renamed the file to 1000.bpm, but it still isn't working.

**Comment by testesneps** [comment]
Just convert your image (jpg,png) to bmp using this https://www.online-convert.com and rename the image to "1000"

**Comment by Heyheu** [comment]
@testesneps i try i convert the photo but still not working ... same problem .. the video virtual mp4 workong good but the image not working .... can u help me plz do u have telegram ?

**Comment by ffreefire2002** [comment]
> 

Did you find a solution?
