### ISSUE TITLE
发现钉钉不生效，是不支持钉钉吗？

### ISSUE THREAD

**Issue by superabbite1** [w2016561536/android_virtual_cam#15]
发现钉钉不生效，是不支持钉钉吗？

**Comment by w2016561536** [comment]
有没有授权钉钉读取本地存储的权限？？
有没有在框架里选择钉钉并重启手机
有没有把virtual.mp4放在正确位置

**Comment by w2016561536** [comment]
不支持virtual xposed ，无root的请用VMOS建立虚拟环境

**Comment by superabbite1** [comment]
已经root的使用的magisk+LSPosed。抖音 高德测试是都可以的，钉钉已经授权了，但是并没有替换

**Comment by w2016561536** [comment]
钉钉会议吗？？你试一下在系统设置里强制停止应用，检查一下钉钉有没有读取存储的权限

**Comment by superabbite1** [comment]
是钉钉打卡，不是钉钉会议，我检查了钉钉的权限 是允许读写手机存储的

**Comment by w2016561536** [comment]
如果是视频，是能被HOOK的，但如果是拍照，需要把目标照片命名为1000.bmp（可以把别的照片改后缀，且不需要匹配分辨率），并放在目录里

**Comment by superabbite1** [comment]
是的，我发现了问题。钉钉和抖音是只能识别到视频（virtual.mp4），如果只设置了照片（1000.bmp）是无效的并不能替换，只有设置视频才能替换。但是高德地图是可以识别到照片的（1000.bmp）。我现在要在钉钉和抖音中使用的话只能将照片制作成MP4格式的视频进行替换 。
