### ISSUE TITLE
i have a problem with the cam

### ISSUE THREAD

**Issue by joefrazier498** [w2016561536/android_virtual_cam#158]
how its working ?

**Comment by westruk** [comment]
SCAM! Refuses to work through escrow! Also cannot provide video evidence that the module is working.

**Comment by joefrazier498** [comment]
did you find a solution ?

**Comment by joefrazier498** [comment]
l

**Comment by westruk** [comment]
> did you find a solution ?

you so stupid scammer

**Comment by alextls128** [comment]
Hi, email me if you still need it. alextls128@gmail.com
