### ISSUE TITLE
开启视频声音后通话结束声音不会消失

### ISSUE THREAD

**Issue by xkldxf** [w2016561536/android_virtual_cam#17]
通话结束视频声音不会消失，QQ微信都这样。微信通话视频被拉伸得很难看，希望优化一下

**Comment by w2016561536** [comment]
视频声音不会消失暂时没法解决
拉伸问题是分辨率和比例不对

发件人: xkldxf
发送时间: 2021年9月8日 8:49
收件人: w2016561536/android_virtual_cam
抄送: Subscribed
主题: [w2016561536/android_virtual_cam] 开启视频声音后通话结束声音不会消失 (#17)

通话结束视频声音不会消失，QQ微信都这样。微信通话视频被拉伸得很难看，希望优化一下

**Comment by w2016561536** [comment]
2.9已解决
