### ISSUE TITLE
I need it to work on [ Facetec ]

### ISSUE THREAD

**Issue by Taym-X** [w2016561536/android_virtual_cam#18]
Thanks to the developer of the application for this wonderful program
The app has been tested on WhatsApp and it works fine
But I need it to work on [ Facetec ]
This is the application link

https://play.google.com/store/apps/details?id=com.facetec.zoomlogin

**Comment by w2016561536** [comment]
It seems that it has been successfully hooked, but app doesn't require storage read permission, and you would get a blanket preview.
If you wan't to let it work, you can use it in a low version Android or edit its permission.

**Comment by Taym-X** [comment]
device system
android 8.0
I want him to work on [ facetec ]
But a blank screen appears and the app stops working

**Comment by w2016561536** [comment]
> device system
> 
> android 8.0
> 
> I want him to work on [ facetec ]
> 
> But a blank screen appears and the app stops working

This will have a solution in ver 3.5, which will release soon

**Comment by Taym-X** [comment]
### Thank you my dear
**Waiting for you
I wish you all the best**

**Comment by Taym-X** [comment]
> > device system
> > android 8.0
> > I want him to work on [ facetec ]
> > But a blank screen appears and the app stops working
> 
> This will have a solution in ver 3.5, which will release soon

How are you dear
Version 3.5 released 3 days ago
 But it did not solve the problem of the FaceTec app

**Comment by w2016561536** [comment]
Have you seen the usage description, I have update it

You need to copy Camera1 directory to specific path

**Comment by w2016561536** [comment]
> > > device system
> > > android 8.0
> > > I want him to work on [ facetec ]
> > > But a blank screen appears and the app stops working
> > 
> > 
> > This will have a solution in ver 3.5, which will release soon
> 
> How are you dear Version 3.5 released 3 days ago But it did not solve the problem of the FaceTec app

The permission problem on android 11 has been solved in ver 3.6 , have a try?

**Comment by Taym-X** [comment]
> > > > device system
> > > > android 8.0
> > > > I want him to work on [ facetec ]
> > > > But a blank screen appears and the app stops working
> > > 
> > > 
> > > This will have a solution in ver 3.5, which will release soon
> > 
> > 
> > How are you dear Version 3.5 released 3 days ago But it did not solve the problem of the FaceTec app
> 
> The permission problem on android 11 has been solved in ver 3.6 , have a try?

I have a problem
The video has been shown in the Facetec app
But the face is not recognized
I wanted it to bypass face protection in some apps

**Comment by w2016561536** [comment]
First you should now that not every app can be successfully hooked, especially the one which uses camera2 api

Second if you use it in test purpose, It's ok

but if you want to bypass face recognition , that's illegal, and i can't help you

**Comment by Taym-X** [comment]
> First you should now that not every app can be successfully hooked, especially the one which uses camera2 api
> 
> Second if you use it in test purpose, It's ok
> 
> but if you want to bypass face recognition , that's illegal, and i can't help you

Of course it is dedicated to testing. Originally, FACETEC is a test application only

**Comment by w2016561536** [comment]
Hello dear ,
The bugs of open camera fail in is solved
Have a try

Remember : only to use it in testing purpose !!

**Comment by w2016561536** [comment]
exception issue has been solved in 3.8 
Have a try?
