### ISSUE TITLE
大佬，可以hook抖音吗

### ISSUE THREAD

**Issue by wangzc1234** [w2016561536/android_virtual_cam#2]
可以调试一下吗，万分感谢！！！

**Comment by w2016561536** [comment]
抖音摄像头预览走的是Surfaceview，因为很少程序用这个的，所以我没做。
我会找个时间加进来

**Comment by w2016561536** [comment]
重新上传了代码，抖音测试通过，目标视频为：/sdcard/DCIM/Camera/virtual.mp4

**Comment by wangzc1234** [comment]
大佬辛苦了！谢谢你！问一下这个可以实现调用mp4的声音吗？

**Comment by w2016561536** [comment]
> 大佬辛苦了！谢谢你！问一下这个可以实现调用mp4的声音吗？

不可以，录制音频和视频是分开的，不是一个类，这个模块只能hook摄像头
