### ISSUE TITLE
这个软件怎么用

### ISSUE THREAD

**Issue by andyhang1980** [w2016561536/android_virtual_cam#20]
已经安装了lsp，勾选了微信，怎么旋转90°？没看懂。

**Comment by w2016561536** [comment]
旋转90度是用剪辑软件旋转

**Comment by rxzcums** [comment]
> 旋转90度是用剪辑软件旋转

作者能推荐一个软件吗？我用前置摄像头录像，在APP里面也是前置摄像头调用，需要水平翻转并右旋90度吗？

**Comment by w2016561536** [comment]
> > 旋转90度是用剪辑软件旋转
> 
> 作者能推荐一个软件吗？我用前置摄像头录像，在APP里面也是前置摄像头调用，需要水平翻转并右旋90度吗？

只要目标app是前置摄像头，基本上都要旋转90
剪辑软件:剪映，爱剪辑，必剪，premiere，达芬奇，FCPX

基本上是个剪辑软件都能胜任

**Comment by rxzcums** [comment]
但一般全压缩，分辨率变化没关系吗

**Comment by w2016561536** [comment]
> 但一般全压缩，分辨率变化没关系吗？哪个是原画质可以翻转旋转的？对了，水平翻转是必须的吗

那要看你所拍摄的画面是不是对称的，例如文字就需要去水平翻转，压缩肯定会带来画质损失，所以转码的时候码率开高一点
分辨率是指旋转完后的分辨率。
