### ISSUE TITLE
Virtual photo not showing in Bumble and Snapchat

### ISSUE THREAD

**Issue by louisfverger** [w2016561536/android_virtual_cam#21]
Thank you very much for your excellent work! I've been looking for such an app for a very long time!
I want to use it on Bumble for live photo verification - it works perfectly in Telegram, but when I try to take a photo in Bumble (https://play.google.com/store/apps/details?id=com.bumble.app&hl=de&gl=US) or Snapchat, it doesn't implement the 1000.bmp and takes a real - not virtual - picture. 
Is there a way to get it work? Any tips would be highly appreciated!

Thanks in advance. 
Louis

**Comment by louisfverger** [comment]
Addition: all apps got storage permission and were selected in the framework.

**Comment by w2016561536** [comment]
Sorry, but there are some bugs with Camera2 API. 
Most of recent launched apps are using Camera2 API due to the Google's strong recommendation .
But in China, most apps is still using Camera API.
I'm trying to solve this problem.

**Comment by Taym-X** [comment]
Thank you w2016561536
we are waiting for you
😘😘😘

**Comment by w2016561536** [comment]
The most problems of camera2 API SHOULD have been solved, you can try new version.

Attention: ONLY virtual.mp4 works in Camera2, 1000.bmp have no effect in camera2
