### ISSUE TITLE
App crash when access to camera

### ISSUE THREAD

**Issue by adamelegord** [w2016561536/android_virtual_cam#22]
Some apps like google meet and chrome will crash when access to camera. There is the log https://hastebin.com/ijoyuyicox
In previous versions vcam v2.5 it runs normally and doesn't crash, And when in v2.6 and v2.7 the app crash, I've tried disabling and enabling cam2api.

**Comment by adamelegord** [comment]
The problem has not been resolved, meet gmail and chrome still crash in version 2.8. there is the log https://hastebin.com/iletonaloh

**Comment by w2016561536** [comment]
But....I have tested on my phone (samsung a60 with Android 11)

Although Chrome will get crash when close the camera( I think it can be fixed.)， The apps runs smoothly.

because Google meet doesn't have access to local storage,  you only can see a blank preview. BUT it wouldn't get crash.

**Comment by adamelegord** [comment]
![Screenshot_20210914-221606521](https://user-images.githubusercontent.com/74820774/133285096-731306c1-ec3d-4384-8bab-564f74570b85.jpg)
hmm.... ok, google meet in gmail app i mean. Maybe it's because I'm using a custom rom. By the way, thank you for your hard work developing vcam for android. Very useful 🙂

**Comment by w2016561536** [comment]
version of 2.9 has successfully fixed the chrome app crash
Have a try!
