### ISSUE TITLE
能否把提示的信息取消掉，禁用后就不要在提示禁用等任何信息了

### ISSUE THREAD

**Issue by sujicheng8** [w2016561536/android_virtual_cam#23]
能否把提示的信息取消掉，禁用后就不要在提示禁用等任何信息了

**Comment by sujicheng8** [comment]
那你有时间快点弄啊，要不你就加个参数关闭提示信息用的就行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w2016561536/android_virtual_cam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w2016561536/android_virtual_cam] 能否把提示的信息取消掉，禁用后就不要在提示禁用等任何信息了 (#23)





 
那得等我把camera2的bug修完，然后就不需要这个提示了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w2016561536** [comment]
2.9把禁用的提示信息删了
