### ISSUE TITLE
能屏蔽麦克风不

### ISSUE THREAD

**Issue by YaJing0412** [w2016561536/android_virtual_cam#24]
某些软件里想要他只播放视频的声音即可，不用把环境音也录进去

**Comment by w2016561536** [comment]
不可以，不静音的原理其实是通过扬声器把声音播放，然后再用麦克风接收。
hook麦克风有点麻烦，暂时没做
（做了也是需要匹配文件信息的（比特率，采样率））

**Comment by ail36413** [comment]
淘宝9.9 买个设备就好了

**Comment by YaJing0412** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
