### ISSUE TITLE
软件扫码黑屏

### ISSUE THREAD

**Issue by noname9528** [w2016561536/android_virtual_cam#25]
描述:同一个手机其他的软件Qq, WeChat, zfb都可以替换视频正常扫码，但这个软件打开扫码一片黑，也没有任何提示。手机摄像头坏了，想用虚拟相机扫码😂希望作者解答一下，十分感谢
软件链接:https://play.google.com/store/apps/details?id=vn.coquan.hd

![Screenshot_2021-09-16-14-29-37-970_org lsposed manager](https://user-images.githubusercontent.com/90825397/133569407-df589d47-bb9a-44fb-a8cc-403394a94331.jpg)

**Comment by w2016561536** [comment]
这个软件我无法登陆，无法触发相机

**Comment by w2016561536** [comment]
一片黑的话你把lsposed里日志给我

**Comment by noname9528** [comment]
[LSPosed_2021-09-16T21_53_07.881.zip](https://github.com/w2016561536/android_virtual_cam/files/7178846/LSPosed_2021-09-16T21_53_07.881.zip)

**Comment by noname9528** [comment]
在日志中看到了软件相机分辨率，之前软件没弹出分辨率，也没想到看日志。明天我匹配下分辨率试一下，再反馈

**Comment by w2016561536** [comment]
你没授予应用访问存储的权限吧

**Comment by noname9528** [comment]
有啊，所有权限都拉满了

**Comment by noname9528** [comment]
[Pass_LSPosed_2021-09-16T23_12_24.275.zip](https://github.com/w2016561536/android_virtual_cam/files/7179380/Pass_LSPosed_2021-09-16T23_12_24.275.zip)
[黑屏LSPosed_2021-09-16T23_13_32.453.zip](https://github.com/w2016561536/android_virtual_cam/files/7179381/LSPosed_2021-09-16T23_13_32.453.zip)
![Screenshot_2021-09-16-23-14-18-437_com miui securitycenter](https://user-images.githubusercontent.com/90825397/133648104-023dcbc5-0079-4c70-876d-a7aecf37c665.jpg)
第一份日志是QQ成功拦截的日志，第二份是黑屏软件的日志。

**Comment by noname9528** [comment]
使用了匹配分辨率的视频，还是黑的😂
com.journeyapps.barcodescanner.CaptureActivity
另外提供个Activity可以调扫码界面，直接触发相机。
需要抓logcat,也可以协助。感谢

**Comment by w2016561536** [comment]
我这里是正常的啊
![Screenshot_20210917-180406.jpg](https://user-images.githubusercontent.com/40821031/133765426-dec33617-fabf-4f1c-8c2c-a5516fa46d35.jpg)

**Comment by noname9528** [comment]
搞不懂，可能是MIUI的锅😢我另寻他法。还是很感谢你
