### ISSUE TITLE
能不能只用于微信呢

### ISSUE THREAD

**Issue by sujicheng8** [w2016561536/android_virtual_cam#26]
能不能只用于微信呢，防止其他应用无法使用相机功能，并且关闭后就不要提示信息什么的了

**Comment by w2016561536** [comment]
edxp和lsposed均支持作用域，在里面选择微信即可

**Comment by sujicheng8** [comment]
还有个事，加你下微信呗，我微信sujicheng8







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w2016561536/android_virtual_cam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 晚上10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w2016561536/android_virtual_cam] 能不能只用于微信呢 (#26)





 
edxp和lsposed均支持作用域，在里面选择微信即可
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
