### ISSUE TITLE
Hallo I just wanna ask,  is it possible to capture with default camera, exclusively for MIUI Rom? 

### ISSUE THREAD

**Issue by amican** [w2016561536/android_virtual_cam#28]
I've been tested with MIUI ROM, it's only work for preview but when i capture image, it show original input hardware camera

**Comment by w2016561536** [comment]
You mean the system camera app, or third-party app?

If you want to hook the image capture. Perhaps you need to create 1000.bmp under the specific path.

If it's convenient for you, send me the log of xposed.

**Comment by fahadpk007** [comment]
Hi. I tried with snapchat and another camera app. But snapchat would give error of no camera detected. I placed virtual.mp4 and 1000.bmp in the specified folder. But still the same issue with both the apps. I tried placing disable.jpg in the specified folder, it let the snapchat app detect camera but no image was replaced. Could you please guide me the proper procedure to get it work and where I am doing something incorrect?

**Comment by w2016561536** [comment]
Er... I have not found the reason
this may be a tough problem

**Comment by fahadpk007** [comment]
Ohh. Do you have it working or tested on snapchat for yourself? May be you will be able to identify the problem. 
If it is convenient for you, could you please prepare a video link for us to understand how to configure this module to work properly? In my case, I may be mixing things up. You tutorial could help me get things sorted. Thanks in advance.

**Comment by w2016561536** [comment]
I have test it, but it reports error (illeagleStateException) when trying to provide content for surface.
till now , I have not found the reason

**Comment by fahadpk007** [comment]
Ohh okay. Hoping for the best and wish it get sorted out asap. Really like the idea of the module. Very best wishes to you bro.

**Comment by w2016561536** [comment]
The snapchat is very strange, even doesn't invoke createCaptureSession.
In most demo app and Camera2 api invoke  tutorials , the method would be invoked when open camera.
Perhaps I need to analyze the code of snap chat.
