### ISSUE TITLE
没想到真的找到了，真厉害！！

### ISSUE THREAD

**Issue by wangzcwhy** [w2016561536/android_virtual_cam#3]
想搞无人直播 声音可以解决吗😀😀😀😀

**Comment by w2016561536** [comment]
有个最简单的方法，我取消静音，然后你把手机扬声器开满

**Comment by w2016561536** [comment]
要想静音注入，有点麻烦，而且很难保持同步

**Comment by wangzcwhy** [comment]
取消静音听起来可以😀好实现吗

**Comment by w2016561536** [comment]
很好搞，就删一条代码

**Comment by w2016561536** [comment]
> 取消静音听起来可以😀好实现吗
直达链接
https://github.com/w2016561536/android_virtual_cam/blob/no-silent/app/release/app-release.apk

**Comment by wangzcwhy** [comment]
> > 取消静音听起来可以😀好实现吗
> > 直达链接
> > https://github.com/w2016561536/android_virtual_cam/blob/no-silent/app/release/app-release.apk

谢谢，我去试试

**Comment by wangzcwhy** [comment]
十分感谢🎉🎉
