### ISSUE TITLE
ding talk 6.0.15 相机卡死

### ISSUE THREAD

**Issue by 0only** [w2016561536/android_virtual_cam#30]
vcam2.8版本正常
2.9/3.0 表现钉钉卡死，不能拍照，请问能修一下不，谢谢大佬

**Comment by w2016561536** [comment]
我这里3.0正常
请问是钉钉什么功能异常
还有截图xposed日志给我，谢谢

**Comment by 0only** [comment]
是钉钉的签到功能，我以装回2.8了

**Comment by w2016561536** [comment]
我能确认的是这三个版本之间，处理拍照的方法没有变

**Comment by w2016561536** [comment]
能否发一下3.0的日志？

**Comment by 0only** [comment]
稍等 我安装一下

**Comment by 0only** [comment]
https://cloud.189.cn/web/share?code=yQbmI3yQRnA3（访问码：9bc1）lsp日志文件

**Comment by 0only** [comment]
java.lang.NoSuchMethodError: android.location.GnssStatus(java.lang.Integer,int[],float[],float[],float[])#bestmatch
 at de.robv.android.xposed.XposedHelpers.findConstructorBestMatch(Unknown Source:127)
 at de.robv.android.xposed.XposedHelpers.findConstructorBestMatch(Unknown Source:4)
 at de.robv.android.xposed.XposedHelpers.newInstance(Unknown Source:0)
 at com.cataclysm.i.f$a.a(Unknown Source:241)
 at com.cataclysm.i.d$2.handleMessage(Unknown Source:31)
 at android.os.Handler.dispatchMessage(Unknown Source:19)
 at android.os.Looper.loop(Unknown Source:242)
 at android.app.ActivityThread.main(Unknown Source:101)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
以上是钉钉报错日志，这个是随机出现的，不知道是不是我的钉钉版本不行，请问大佬用的是哪个版本的钉钉呢

**Comment by w2016561536** [comment]
你伪装定位炸了吧，报的错是GnssStatus获取错误（没有找到这个方法）
我的是6.0.30

**Comment by 0only** [comment]
钉钉报错也该是定位问题，我用的是lataclysm，不知道还有其他插件替代不
vcam2.8倒是没有问题，钉钉报错java.lang.NoSuchMethodError:只要打开一次定位就行了

**Comment by w2016561536** [comment]
findConstructorBestMatch

那个作者用到了查询功能
可能误将我注入的东西匹配到了

**Comment by 0only** [comment]
虚拟定位是刚需嘿
那就是和钉钉的版本没有多大的关系咯，有办法修吗？

**Comment by w2016561536** [comment]
应该可以。。你试一下
[app-release.zip](https://github.com/w2016561536/android_virtual_cam/files/7203267/app-release.zip)

**Comment by 0only** [comment]
[LSPosed_2021-09-21T21_16_02.555.zip](https://github.com/w2016561536/android_virtual_cam/files/7203316/LSPosed_2021-09-21T21_16_02.555.zip)

**Comment by 0only** [comment]
[LSPosed_2021-09-21T21_23_01.849.zip](https://github.com/w2016561536/android_virtual_cam/files/7203402/LSPosed_2021-09-21T21_23_01.849.zip)
这是我关闭lataclysm后打卡签到卡死的日志

**Comment by w2016561536** [comment]
我试了一下这个模块
他不是跟我注入的东西打架
他是跟我的注入方法打架
但是我这里可以正常使用。

这个解决起来就非常麻烦了。（不太清楚为什么作者要查找这个不太安全的东西）
https://user-images.githubusercontent.com/40821031/134178829-e2d2c2f8-33c8-49e6-93e8-5945bc1fa302.mp4

**Comment by 0only** [comment]
那有什么好的定位插件，替换他

**Comment by w2016561536** [comment]
我暂时没有用过，无法做出推荐。
但是我这里用你所提供的模块是正常的（虽然会报错），点完拍照以后可以等一个两三秒试一下。

**Comment by 0only** [comment]
我刚升级了钉钉6.0.30，禁用了lataclysm 还是一样，拍照无预览，点击拍照就挂了

**Comment by w2016561536** [comment]
日志上显示21:22:47时成功HOOK预览信息，然后没有下文了，我也不清楚是什么导致他闪退了

**Comment by w2016561536** [comment]
感谢你对此项目的支持！

**Comment by 0only** [comment]
恩恩，辛苦了，我装回2.8和钉钉6.0.15了

**Comment by w2016561536** [comment]
能否试一下3.3版本，应该是修复了

**Comment by 0only** [comment]
谢谢 ，试过了，还是老样子，卡死

**Comment by w2016561536** [comment]
那我这就不清楚了，不过谢谢

**Comment by w2016561536** [comment]
的确我也出发了这个问题（概率触发）
可能跟Android版本有关
我安卓11上没问题，但是转到VMOS中使用安卓5.0触发了这个问题
![Screenshot_20211001-231917_VMOS.jpg](https://user-images.githubusercontent.com/40821031/135646340-a21e6f78-5425-487b-ad4c-c436a85fafe3.jpg)

**Comment by 0only** [comment]
感谢大佬，3.4不仅相机可以预览，拍照也不卡了

**Comment by w2016561536** [comment]
感谢对此项目的支持
但是我回去看了我的提交记录，我也不清楚怎么解决的🤣
