### ISSUE TITLE
video playback problem on meet gmail

### ISSUE THREAD

**Issue by adamelegord** [w2016561536/android_virtual_cam#31]
Vcam v3.0 | Virtual cam meet on gmail, i have 2 minutes video but the video does not play full video, the video only plays for 13 seconds and then returns to the beginning, After looping the third time the video will be stuck and the camera will automatically turn off, And while i turn camera back on the virtual cam only appears for 1 second and camera automatically turn back off, I have screen record the problem, here is the link https://drive.google.com/file/d/1mj3o_kne-9zhKHQ_sh9KsQPGSIbEQUKx/view

And on chrome the camera is black?
![Screenshot_20210922-161155873](https://user-images.githubusercontent.com/74820774/134316480-342e3694-3f30-441e-b298-a50a201d3f55.jpg)

Does this problem occur on your phone?

**Comment by w2016561536** [comment]
Yeah, i've found the problem on my phone

It seems to be that Google meet detect that the camera isn't correctly opened.

And sometimes snapchat will occur the same problem,  and the APP will directly reported that the camera isn't correctly opened.

According to the xposed log,  I found a strange camera open process.

However, in some Google apps,  Like Google translate. Will not occur this problem.

**Comment by adamelegord** [comment]
Yeah, actually there is no problem if cam2api is disabled, but if disabling cam2api the audio from the video is piled up, I use the audio as well by inputting it using a splitter.

And on zoom meeting, the video is green 😂
![Screenshot_20210922-232835776](https://user-images.githubusercontent.com/74820774/134384322-53da6406-dd45-4718-b909-c26ffa28c2f9.jpg)

**Comment by w2016561536** [comment]
> Yeah, actually there is not occur if cam2api is disabled, but if disabling cam2api the audio from the video is piled up, I use the audio as well by inputting it using a splitter.
> 
> And on zoom meeting, the video is green 😂
> ![Screenshot_20210922-232835776](https://user-images.githubusercontent.com/74820774/134384322-53da6406-dd45-4718-b909-c26ffa28c2f9.jpg)
> 

Have you ever seen the toast message written in Chinese.  It indicates the original resolution.
The video resolution for zoom must be 640*480

**Comment by w2016561536** [comment]
now I think it can function properly in google meet in gmail
would you like to have a try v3.3 ?
