### ISSUE TITLE
钉钉打卡提示未识别到人脸

### ISSUE THREAD

**Issue by Jieoz** [w2016561536/android_virtual_cam#32]
替换视频正常显示，但是提示识别不到人脸，同样画面不用插件正常打卡，3.0版本

**Comment by w2016561536** [comment]
前置摄像头需要右旋90°
分辨率为640*480

我确认是可用的

**Comment by Jieoz** [comment]
大佬分辨率是640x480是顺时针旋转90°之后还是旋转之前。

我这边录制1920x1080右旋后钉钉里显示的非常扭曲但是依旧不能识别到人脸。调整到正常方向显示正常但是钉钉还是识别不到。

我再试试640x480

**Comment by w2016561536** [comment]
是旋转之后的分辨率，多一像素少一像素都不行。

**Comment by Jieoz** [comment]
成功了，谢谢大佬
