### ISSUE TITLE
钉钉签到无法替换图片

### ISSUE THREAD

**Issue by tongcheung0218** [w2016561536/android_virtual_cam#34]
在拍照的时候直接就卡死了

**Comment by w2016561536** [comment]
能否提供一下滚动到底部的日志截图
反馈这个bug的不是你一个人
但我没触发过这个bug

**Comment by gao306411** [comment]
前面更新的版本取消视频替换够微信扫码相机都会卡死，哟都试了一下只有版本2.3不会卡死正常！！！

**Comment by w2016561536** [comment]
> 前面更新的版本取消视频替换够微信扫码相机都会卡死，哟都试了一下只有版本2.3不会卡死正常！！！

日志能发一下？

**Comment by w2016561536** [comment]
能试一下3.3版本吗，应该是修复了
