### ISSUE TITLE
外勤365怎么hook  

### ISSUE THREAD

**Issue by nimaaaazz** [w2016561536/android_virtual_cam#37]
打开就是提示不存在替换视频，然后加了个视频，直接app就卡死了，然后就是我这个app只想替换照片该怎么去操作，

**Comment by nimaaaazz** [comment]
在camera1目录里放置1000.bmp识别不出来，还是提示未不存在替换视频

**Comment by rxzcums** [comment]
放virtual.mp4

**Comment by w2016561536** [comment]
3.3版本应该修复了卡住的bug
