### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by pharsyde2227** [w2016561536/android_virtual_cam#38]
Hi. When the application asks for camera it freezes and crashes. the resolution shows 1440x1080 i put the correct mp4 and bmp there and it crashes. i tried a bunch of pictures however same result. perhaps the problem is that it uses different camera api? i also tried to put disable.jpg, still same result. just oval field for face and dark screen then crash. please help what can be wrong. whatsapp works properly

**Comment by w2016561536** [comment]
can you tell me the app's name and provide xposed log?

**Comment by w2016561536** [comment]
Can you try the new version?
3.3 has fixed many bugs in Camera2, and now it can work properly in gmail
