### ISSUE TITLE
wei

### ISSUE THREAD

**Issue by qloop1** [w2016561536/android_virtual_cam#39]
微信8.0.15，按要求操作，扫一扫可以显示视频，但是扫不了视频里面的二维码，支付宝却可以扫到视频里面的码。微信拦截拍照照片，照片改成1000.bmp，分辨率改成1280x720，一直没拦截成功过。

**Comment by w2016561536** [comment]
你确定分辨率对吗
微信二维码扫描我记得是1920*1080
微信的拍照hook是看的virtual.mp4

**Comment by w2016561536** [comment]
https://user-images.githubusercontent.com/40821031/135583189-6b50f34d-5d82-4c31-b7dc-662ce54277f6.mp4

因为手机在录屏，DSP有点忙不过来

**Comment by qloop1** [comment]
大哥，你好，看了你的视频的确是微信扫码成功了，我的视频分辨率是720x1480，我同样的mp4，微信扫一扫只会播放mp4，却不会识别其中的二维码，同样的支付宝就可以扫识别里面的二维码。微信版本是8.0.15，不知道你的微信版本是多少。
还有就是，Camera1里面不放mp4，微信扫一扫就会卡死。，支付宝不会卡死。
还有就是1000.bmp按照你说的分辨率，调整了放入Camera1，打开拍照不拦截，支付宝也无效。

---Original---
From: ***@***.***&gt;
Date: Fri, Oct 1, 2021 15:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [w2016561536/android_virtual_cam] wei (#39)




 
https://user-images.githubusercontent.com/40821031/135583189-6b50f34d-5d82-4c31-b7dc-662ce54277f6.mp4
 
因为手机在录屏，DSP有点忙不过来
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w2016561536** [comment]
就是因为1000.bmp，我修改了readme

不是所有应用都会去调取这张图片，只有在底下弹出发现拍照的时候才需要使用这张图片

在打开相机，如果底下弹出了"宽:  高:  帧率:"
那必须完全按照分辨率制作视频

**Comment by gao306411** [comment]
大哥，能不能匹配一下微信低版本！比如微信7.0.6用起顺畅还不占内存！！！ 主要现在的高版本微信太拖内存了卡的很用起一点也不习惯！我都测试了一下只有微信8.0.7以上版本一切都正常！！！

**Comment by gao306411** [comment]
大哥！可以匹配一下微信低版本吗！比如微信7.0.6用起顺畅还不占内存！！！ 主要现在的高版本微信太拖内存了而且还卡的很，用习惯了低版本用高版本一点都不顺手！我都测试了一下只有微信8.0.7及以上版本一切都正常！
