### ISSUE TITLE
大神，这个项目怎么使用的呀

### ISSUE THREAD

**Issue by iamluyou** [w2016561536/android_virtual_cam#4]
需要安装VirtualXposed吗，还是别的什么

**Comment by w2016561536** [comment]
我无法确认虚拟框架是否能用。
1、 在/sdcard/DCIM/Camera目录下放置virtual.mp4，用于预览HOOK。
2、 使用PR等剪辑软件将视频逐帧拆解，导出为BMP格式，命名格式在readme，然后将这些图片放在/sdcard/DCIM/Camera/bmp目录下，用于回调HOOK
3、 回调HOOK用的图片必须和软件申请的像素大小相等（在软件使用摄像头回调的时候，你可以在xposed日志中找到“初始化预览回调 宽…高…”）
4、对于大多数软件，只需要/sdcard/DCIM/Camera目录下放置virtual.mp4（特例：腾讯会议必须使用回调HOOK,像素值640*480）

**Comment by iamluyou** [comment]
多谢多谢，我研究下
