### ISSUE TITLE
微信扫一扫可以识别了

### ISSUE THREAD

**Issue by qloop1** [w2016561536/android_virtual_cam#40]
微信扫一扫，二维码，可以识别了，分辨率要一致。
支付宝就不用 匹配分辨率，就可以识别。目前比较好用

**Comment by w2016561536** [comment]
感谢反馈
微信和支付宝二维码扫描用的不是一种api
请问如果按你的理解，readme怎么修改比较合适

**Comment by rxzcums** [comment]
微信扫一扫为什么要hook，直接从相册

**Comment by w2016561536** [comment]
> 微信扫一扫为什么要hook，直接从相册

我估摸着可能只是测试

**Comment by qloop1** [comment]
大哥，你好，我对readme这方面不懂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月2日(周六) 中午1:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [w2016561536/android_virtual_cam] 微信扫一扫可以识别了 (#40)




 
感谢反馈
 微信和支付宝二维码扫描用的不是一种api
 请问如果按你的理解，readme怎么修改比较合适
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w2016561536** [comment]
> 大哥，你好，我对readme这方面不懂
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年10月2日(周六) 中午1:31 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [w2016561536/android_virtual_cam] 微信扫一扫可以识别了 (#40) 感谢反馈 微信和支付宝二维码扫描用的不是一种api 请问如果按你的理解，readme怎么修改比较合适 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Emmm，我的意思是，如果对介绍（使用方法）有建议的，欢迎提出建议。
