### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zqply** [w2016561536/android_virtual_cam#42]
快手花屏，抖音视频反转是怎么回事？

**Comment by w2016561536** [comment]
花屏是分辨率不对，方向错误的话请处理原视频。

**Comment by zqply** [comment]
只有原相机录制的视频可以，其他的视频即使分辨率和帧率都是对的也是花屏，原相机录制的视频不做分辨率和帧率的修改，只分割视频也是花屏

**Comment by w2016561536** [comment]
能发一下花瓶的视频样本吗
