### ISSUE TITLE
能不能解决一下微信视频让对方听替换视频播放的声音

### ISSUE THREAD

**Issue by gao306411** [w2016561536/android_virtual_cam#44]
能不能解决一下微信视频让对方听替换视频播放的声音！！！还有能不能匹配一下微信低版本都测试了一遍只有8.0.7及以上的版本正常工作！ 我用习惯了微信7.0.6！！
![Screenshot_2021-10-10-05-09-11-733_com tencent mm](https://user-images.githubusercontent.com/59394204/136674040-a7b9a8b0-0f6a-455c-854a-7fc19f834102.jpg)

**Comment by kokocooler2020** [comment]
请问本机用了假视频后, 与其他人微信视频, 对方能看到我的假视频吗

**Comment by w2016561536** [comment]
可以
