### ISSUE TITLE
Doesn't work in Bluestack emulator

### ISSUE THREAD

**Issue by xingyunjohn1** [w2016561536/android_virtual_cam#47]
`Android 7.1` & `Xposed`: Tested with `system camera` and code scanner in `via explorer`. The former one throws an error and the latter one scans a black scene.
A toast threw, with resolution information, when the first time I used it. However, the toast never appeared though the `virtual.mp4` was deleted in the rest times.

**Comment by w2016561536** [comment]
the system camera, because it uses some special API so it can’t be hooked

The next one ,did the app has permission to access local storage?
