### ISSUE TITLE
这么久了怎么一直没有看见有新功能更新

### ISSUE THREAD

**Issue by gao306411** [w2016561536/android_virtual_cam#51]
我一直在等更新新的功能！这么久了怎么一直没有看见有新功能更新呢！！！

**Comment by qkkas** [comment]
作者可以试试腾讯会议，不咋好使，为什么不能自动匹配分辨率呢

**Comment by w2016561536** [comment]
腾讯会议试过了可以的
我网课腾讯会议
需要分辨率640*480
需要在系统设置中授权“允许访问存储”

没有自动分辨率原因两点
1卡顿
2不好控制缩放，平移
所以干脆要求完全匹配
