### ISSUE TITLE
已知问题

### ISSUE THREAD

**Issue by w2016561536** [w2016561536/android_virtual_cam#54]
CameraX库在安卓9.0上，由于自动选取最新API，导致配置时相机没有被HOOK到，将“尝试”在下个版本修复。（改了不是一点东西）

也包括完全按照谷歌规定，使用Camera2的库，但使用最新API的应用程序，导致报告打开相机失败的情况。

**Comment by AgentKirito** [comment]
企业微信定制后台打卡，需要拍照，应该是通过H5直接请求相机，测试安卓5.1虚拟机（VMOS）下可以正常Hook并替换，安卓7.1( VMOS)下可以hook onpreview（预览替换为mp4）但拍照报错（估计是通过camera2 api控制拍照），安卓11( Pixel 3)下hook不生效（估计是由于cameraX api），供参考。期待更新（在被窝里打卡全靠它了）

**Comment by w2016561536** [comment]
> 企业微信定制后台打卡，需要拍照，应该是通过H5直接请求相机，测试安卓5.1虚拟机（VMOS）下可以正常Hook并替换，安卓7.1( VMOS)下可以hook onpreview（预览替换为mp4）但拍照报错（估计是通过camera2 api控制拍照），安卓11( Pixel 3)下hook不生效（估计是由于cameraX api），供参考。期待更新（在被窝里打卡全靠它了）

首先，我不建议你这么做
第二，反馈bug，请附上xposed日志

**Comment by qkkas** [comment]
一开始腾讯会议提示1280×720，后来变成640×360了，画面就糊了，应该怎么办？

**Comment by w2016561536** [comment]
> 一开始腾讯会议提示1280×720，后来变成640×360了，画面就糊了，应该怎么办？

画面糊了，就是分辨率不对。

**Comment by AgentKirito** [comment]
> 

----part 1 start----
[ 2021-11-24T13:26:01.133    10272:  4072:  4072 I/LSPosed-Bridge  ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk
[ 2021-11-24T13:26:01.502    10272:  4072:  4072 I/LSPosed-Bridge  ]   Loading class com.cataclysm.i.MainHook
[ 2021-11-24T13:26:01.522    10272:  4072:  4072 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk
[ 2021-11-24T13:26:01.549    10272:  4072:  4072 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain
[ 2021-11-24T13:26:11.932    10272:  6031:  6031 I/LSPosed-Bridge  ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk
[ 2021-11-24T13:26:11.970    10272:  6031:  6031 I/LSPosed-Bridge  ]   Loading class com.cataclysm.i.MainHook
[ 2021-11-24T13:26:11.974    10272:  6031:  6031 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk
[ 2021-11-24T13:26:11.976    10272:  6031:  6031 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain
[ 2021-11-24T13:26:14.523    10253:  6218:  6218 I/LSPosed-Bridge  ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk
[ 2021-11-24T13:26:14.559    10253:  6218:  6218 I/LSPosed-Bridge  ]   Loading class com.cataclysm.i.MainHook
[ 2021-11-24T13:26:16.884    10249:  6468:  6468 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk
[ 2021-11-24T13:26:16.888    10249:  6468:  6468 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain
[ 2021-11-24T13:26:19.932    10272:  6643:  6643 I/LSPosed-Bridge  ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk
[ 2021-11-24T13:26:19.975    10272:  6643:  6643 I/LSPosed-Bridge  ]   Loading class com.cataclysm.i.MainHook
[ 2021-11-24T13:26:19.980    10272:  6643:  6643 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk
[ 2021-11-24T13:26:19.982    10272:  6643:  6643 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain
[ 2021-11-24T13:27:28.683    10272: 10532: 10532 I/LSPosed-Bridge  ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk
[ 2021-11-24T13:27:28.789    10272: 10532: 10532 I/LSPosed-Bridge  ]   Loading class com.cataclysm.i.MainHook
[ 2021-11-24T13:27:28.800    10272: 10532: 10532 I/LSPosed-Bridge  ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk
[ 2021-11-24T13:27:28.804    10272: 10532: 10532 I/LSPosed-Bridge  ]   Loading class com.example.vcam.HookMain

**Comment by w2016561536** [comment]
> > 
> 
> ----part 1 start---- [ 2021-11-24T13:26:01.133 10272: 4072: 4072 I/LSPosed-Bridge ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk [ 2021-11-24T13:26:01.502 10272: 4072: 4072 I/LSPosed-Bridge ] Loading class com.cataclysm.i.MainHook [ 2021-11-24T13:26:01.522 10272: 4072: 4072 I/LSPosed-Bridge ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk [ 2021-11-24T13:26:01.549 10272: 4072: 4072 I/LSPosed-Bridge ] Loading class com.example.vcam.HookMain [ 2021-11-24T13:26:11.932 10272: 6031: 6031 I/LSPosed-Bridge ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk [ 2021-11-24T13:26:11.970 10272: 6031: 6031 I/LSPosed-Bridge ] Loading class com.cataclysm.i.MainHook [ 2021-11-24T13:26:11.974 10272: 6031: 6031 I/LSPosed-Bridge ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk [ 2021-11-24T13:26:11.976 10272: 6031: 6031 I/LSPosed-Bridge ] Loading class com.example.vcam.HookMain [ 2021-11-24T13:26:14.523 10253: 6218: 6218 I/LSPosed-Bridge ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk [ 2021-11-24T13:26:14.559 10253: 6218: 6218 I/LSPosed-Bridge ] Loading class com.cataclysm.i.MainHook [ 2021-11-24T13:26:16.884 10249: 6468: 6468 I/LSPosed-Bridge ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk [ 2021-11-24T13:26:16.888 10249: 6468: 6468 I/LSPosed-Bridge ] Loading class com.example.vcam.HookMain [ 2021-11-24T13:26:19.932 10272: 6643: 6643 I/LSPosed-Bridge ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk [ 2021-11-24T13:26:19.975 10272: 6643: 6643 I/LSPosed-Bridge ] Loading class com.cataclysm.i.MainHook [ 2021-11-24T13:26:19.980 10272: 6643: 6643 I/LSPosed-Bridge ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk [ 2021-11-24T13:26:19.982 10272: 6643: 6643 I/LSPosed-Bridge ] Loading class com.example.vcam.HookMain [ 2021-11-24T13:27:28.683 10272: 10532: 10532 I/LSPosed-Bridge ] Loading module com.cataclysm.i from /data/app/~~jBnWvrSFJnaE5H5YZ0ee1Q==/com.cataclysm.i-LDJvMwdhHXAMirUX2DF3Og==/base.apk [ 2021-11-24T13:27:28.789 10272: 10532: 10532 I/LSPosed-Bridge ] Loading class com.cataclysm.i.MainHook [ 2021-11-24T13:27:28.800 10272: 10532: 10532 I/LSPosed-Bridge ] Loading module com.example.vcam from /data/app/~~h5QfrfuYhU2sViTOaWmatw==/com.example.vcam-QZiAfa4G3vqpicXoyL5Txw==/base.apk [ 2021-11-24T13:27:28.804 10272: 10532: 10532 I/LSPosed-Bridge ] Loading class com.example.vcam.HookMain

emmm这根本没触发模块的任何功能（或者这个日志是无效的）

**Comment by wgn2015** [comment]
redmi note 8  miui12.0.3版本上，启动相机提示无法连接相机，尝试解决失败，大佬有时间帮忙看下 ，报错信息：
E/CAM_MiCamera2: Failed to resume preview, IllegalState
    java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
        at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:738)
        at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1079)
        at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1127)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:298)
        at com.android.camera2.MiCamera2.resumePreview(MiCamera2.java:22)
        at com.android.camera.module.BaseModule.accept(BaseModule.java:10)
        at com.android.camera.module.BaseModule.accept(BaseModule.java:1)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:2)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:8)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:3)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:2)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/CAM_CameraErrorCallback: onCameraError: other error 256

**Comment by w2016561536** [comment]
> redmi note 8  miui12.0.3版本上，启动相机提示无法连接相机，尝试解决失败，大佬有时间帮忙看下 ，报错信息：
> 
> E/CAM_MiCamera2: Failed to resume preview, IllegalState
> 
>     java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
> 
>         at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:738)
> 
>         at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1079)
> 
>         at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1127)
> 
>         at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:298)
> 
>         at com.android.camera2.MiCamera2.resumePreview(MiCamera2.java:22)
> 
>         at com.android.camera.module.BaseModule.accept(BaseModule.java:10)
> 
>         at com.android.camera.module.BaseModule.accept(BaseModule.java:1)
> 
>         at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:2)
> 
>         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:8)
> 
>         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:3)
> 
>         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:2)
> 
>         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:1)
> 
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 
>         at java.lang.Thread.run(Thread.java:919)
> 
> E/CAM_CameraErrorCallback: onCameraError: other error 256
> 
> 
> 
> 
> 
> 

不接受系统相机bug反馈，抱歉。
CameraX库还没有好的解决方案，会报错存在未配置的Surface

**Comment by w2016561536** [comment]
有问题请新开issues
不受理系统相机问题
