### ISSUE TITLE
安卓11微信无法直接读取data文件夹下文件

### ISSUE THREAD

**Issue by Ceiso1** [w2016561536/android_virtual_cam#56]
已经在气泡提示的
/storage/emulated/0/Android/data/com.tencent.mm/files/Camera1/

新建camera1文件夹且放入virtual.mp4文件
但由于安卓11的缘故 微信依然无法读取到
请问这种情况怎么解决..
在特殊应用权限的访问所有文件里
也没能找到微信进行授予权限

**Comment by w2016561536** [comment]
在设置里直接授予微信读取存储目录的权限，然后使用默认路径
或者你把日志发一下

**Comment by Ceiso1** [comment]
--part 3 start--
2021-11-23T01:45:33.662	10297:29686:29686/	
LSPosed-Bridge ]Loading module com.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-B_peaZsMF3ciCzfpp2Y0qA==/base.apk
2021-11-23T01:45:33.663	10297:29686:	
29686I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:34.670	10297:29842:29842I/	
LSPosed-Bridge]Loadingmodule com.example.vcam from /data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/
com.example.vcam-B_peaZsMF3ciCzfpp2Y0qA==/base.apk
2021-11-23T01:45:34.672	10297:29842:	
29842I/LSPosed-Bridge ]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:35.829	10297:30065:30065I/	
LSPosed-Bridge]Loading modulecom.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
[2021-11-23T01:45:35.831	10297:30065:	
30065 I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:35.970	10297:30095:30095I	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
2021-11-23T01:45:35.973	10297:30095:	
30095 I/LSPosed-Bridge ]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:38.804	10297:30608:30608I/	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-B_peaZsMF3ciCzfpp2Y0qA==/base.apk
2021-11-23T01:45:38.806	10297:30608:	
30608I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:38.863	10297:30633:30633I/	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
2021-11-23T01:45:38.865	10297:30633:	
30633I/LSPosed-Bridge1	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:39.757	10297:30839:30839/	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
2021-11-23T01:45:39.759	10297:30839:	
30839I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:45.272	10324:31295:31295/	
SPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/01:54

日志
模块日志	LSPosed日志	
--part 3 start--
2021-11-23T01:45:33.662	10297:29686:29686/	
LSPosed-Bridge ]Loading module com.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-B_peaZsMF3ciCzfpp2Y0qA==/base.apk
2021-11-23T01:45:33.663	10297:29686:	
29686I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:34.670	10297:29842:29842I/	
LSPosed-Bridge]Loadingmodule com.example.vcam from /data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/
com.example.vcam-B_peaZsMF3ciCzfpp2Y0qA==/base.apk
2021-11-23T01:45:34.672	10297:29842:	
29842I/LSPosed-Bridge ]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:35.829	10297:30065:30065I/	
LSPosed-Bridge]Loading modulecom.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
[2021-11-23T01:45:35.831	10297:30065:	
30065 I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:35.970	10297:30095:30095I	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
2021-11-23T01:45:35.973	10297:30095:	
30095 I/LSPosed-Bridge ]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:38.804	10297:30608:30608I/	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-B_peaZsMF3ciCzfpp2Y0qA==/base.apk
2021-11-23T01:45:38.806	10297:30608:	
30608I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:38.863	10297:30633:30633I/	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSiPzlQqRJF1mgfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
2021-11-23T01:45:38.865	10297:30633:	
30633I/LSPosed-Bridge1	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:39.757	10297:30839:30839/	
LSPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/
com.example.vcam-BpeaZsMF3ciCzfpp2Y0gA==/base.apk
2021-11-23T01:45:39.759	10297:30839:	
30839I/LSPosed-Bridge]	Loading class	
com.example.vcam.HookMain
2021-11-23T01:45:45.272	10324:31295:31295/	
SPosed-Bridge]Loading module com.example.vcam from/data/app/~~CGpHvmSjPzlQqRJF1mqfvQ==/


基本全是这样的

**Comment by Ceiso1** [comment]
data目录下的微信根目录里建了camera1 QQ没有建 一直弹气泡提示...一加9已刷magisk 好像没法主动授予微信QQ访问所有文件的权限 请求了才能授权 没法主动授权..面具也没法直接给root..

**Comment by w2016561536** [comment]
> data目录下的微信根目录里建了camera1 QQ没有建 一直弹气泡提示...一加9已刷magisk 好像没法主动授予微信QQ访问所有文件的权限 请求了才能授权 没法主动授权..面具也没法直接给root..

授权在系统设置里授权读取存储
没法授权的可以在data里放

不要以root身份复制文件，可能无法读取

**Comment by Ceiso1** [comment]
系统只能授权微信访问所有类型文件 但读不到data 要读到data的要授予特殊应用权限 但这个得要微信请求授予才行 也就是说不能主动授权..然后如果只有那个访问所有类型文件的权限的话 就会弹出气泡提示那个路径...

**Comment by w2016561536** [comment]
给微信权限以后就使用默认的路径，而不是气泡里的

**Comment by w2016561536** [comment]
授权了还有的话，估计是应用没重启

**Comment by Ceiso1** [comment]
已经在设置的应用管理里强行停止了 再打开微信依然弹气泡 授权的访问所有类型文件 好像也就只能用于发送文件跟读取相册跟视频..

**Comment by w2016561536** [comment]
emmm，这就很奇怪了，日志里啥也没有

**Comment by Ceiso1** [comment]
我重新装回3.4版本的发现没问题
但竖屏的视频是横屏播放的..拉伸得很奇怪..
然后想着视频右转90° 发现更奇怪了..

**Comment by w2016561536** [comment]
这是个bug。。。。定位到问题了

**Comment by w2016561536** [comment]
> 我重新装回3.4版本的发现没问题
> 但竖屏的视频是横屏播放的..拉伸得很奇怪..
> 然后想着视频右转90° 发现更奇怪了..

这个正常，所以需要调整视频的角度。

**Comment by Ceiso1** [comment]
能不能设置一下按照视频原分辨率播放 这样容易操作一些..

**Comment by Ceiso1** [comment]
对不上的用填充黑边的方式解决

**Comment by w2016561536** [comment]
那我是缩放到填满画面，还是显示完整图像，缩放的时候是否需要保持长宽比，保持长宽比的话保持什么画面在界面内？
这些都是要考虑的问题，每个人选择不一样。

再者，安卓碎片化的问题，相机API都有好几个，每个API都不一样，你看到的，不一定是应用接受到的。
所以才有了指定分辨率，来保证1：1映射。

而且，没有分辨率转换，手机DSP压力小一些（毕竟应用程序可能还需要DSP资源来编码视频）

**Comment by Ceiso1** [comment]
不晓得可不可以将这些封装到插件里 然后让插件使用者自行设置是否缩放等 分辨率的问题的话也通过使用者自行配置来实现 不过感觉对你的工作量应该挺大的...

**Comment by w2016561536** [comment]
安卓11的权限问题已经在3.6版本解决了，尝试一下？？

**Comment by Ceiso1** [comment]
已经好了
