### ISSUE TITLE
能不能做一个视频切换的小工具

### ISSUE THREAD

**Issue by luqitai** [w2016561536/android_virtual_cam#57]
我在B站上看到了有人发布视频切换的小工具，我感觉那个小工具并不完善，还有些问题想请教，我在B站上给您私信了，看一下。有项目想对接下。

**Comment by w2016561536** [comment]
抱歉，我暂时没有时间全时间投入开发
如果你需要接口，我可以告诉你

**Comment by trizau** [comment]
你们用这东西干啥，我正在开发iOS的🤷‍♂️

同样也处于开发中，现阶段演示 :
https://youtu.be/Hnjq-whLWpY
