### ISSUE TITLE
为什么谷歌浏览器拍照后的图片是黑白的？

### ISSUE THREAD

**Issue by youngkangrui** [w2016561536/android_virtual_cam#58]
在谷歌浏览器拍照是黑白的
在其他应用拍照都是彩色
已知条件：
谷歌浏览器拍照能确定用的是mp4替换
其他应用拍照用的是1000.bmp替换

**Comment by w2016561536** [comment]
emmm你确定是图片黑白的？？
我这边是谷歌全家桶都没法显示视频（oneui2.0 安卓10）
安卓11貌似是正常的
能否发一下安卓版本和厂商系统的名字，还有xposed日志

**Comment by w2016561536** [comment]
试试谷歌翻译？
或者Gmail

**Comment by youngkangrui** [comment]
![下载 (4)](https://user-images.githubusercontent.com/23549507/143365597-c8e2b64c-2c25-4c62-84f2-3de965c51a49.jpeg)

拍完照后类似这种黑白颜色，原视频里是彩色的

**Comment by w2016561536** [comment]
能否在谷歌翻译，Gamil应用测试一下？？
很奇怪的问题

**Comment by youngkangrui** [comment]
在谷歌浏览器上试了网页版谷歌翻译，浏览器会拉起系统相机，此时是可以正常hook，但是我的测试用例中，浏览器会直接调用摄像头，就会导致颜色不对

**Comment by w2016561536** [comment]
> 在谷歌浏览器上试了网页版谷歌翻译，浏览器会拉起系统相机，此时是可以正常hook，但是我的测试用例中，浏览器会直接调用摄像头，就会导致颜色不对，
> 
> 大佬有什么思路嘛 我可以自己研究下

红蓝色不分的那种吗，是的话我也在想是为啥（就谷歌翻译有这bug）

**Comment by w2016561536** [comment]
可能是YUV色彩的问题

就是Y通道数据是对的，但是VU这两个通道数据错误

但是为了执行效率和便捷性，我是直接把应用程序的surface交给系统处理，理论上不应该有这个问题

（代码水平十分有限，可能难以阅读）

**Comment by youngkangrui** [comment]
可以这样复现：
1 在浏览器打开https://coding.zhangbing.site/view.html?url=./list/camera-api/index.html
这个网址会直接拉起摄像头
2 可以看到预览视频就是灰色的

**Comment by w2016561536** [comment]
> 可以这样复现：
> 
> 1 在浏览器打开https://coding.zhangbing.site/view.html?url=./list/camera-api/index.html
> 
> 这个网址会直接拉起摄像头
> 
> 2 可以看到预览视频就是灰色的
> 
> 

我得先更新到安卓11，安卓10直接黑屏

**Comment by youngkangrui** [comment]
> 

复现环境是安卓8

**Comment by w2016561536** [comment]
很奇怪
我是用VMOS虚拟的安卓7.1环境

but
在vmos里，即使是没有开启xposed，预览也是黑白的

**Comment by w2016561536** [comment]
很抱歉，这个问题可能真的和系统底层有关，我安卓11，安卓10(one ui)就没有这个bug
