### ISSUE TITLE
关于1000.bmp的问题。

### ISSUE THREAD

**Issue by lsb2005** [w2016561536/android_virtual_cam#59]
您好，钉钉模拟拍照调用1000.bmp的时候，拍摄出来的图片自动向右旋转了90度，除非把1000.bmp的原图向左旋转90度保存，钉钉拍出来才是正的。除了手动将原图向左旋转90度以外，源码该修改哪儿才可以不用将调用的图片左旋转90度呢？？望指点。。

**Comment by w2016561536** [comment]
有些麻烦，我现在没有查到能直接旋转JPEG的方法
可能先要把图片转换成bitmap（代码中为变量pict），然后旋转，然后再转回JPEG（pict.compress），最后替换掉原来的jpeg_data
相关代码在HookMain.java:822

**Comment by lsb2005** [comment]
万分感谢百忙之中过来解答，希望在以后的版本中可以得到解决，奥力给……。我也去琢磨琢磨。
