### ISSUE TITLE
手机启动不了

### ISSUE THREAD

**Issue by netstu** [w2016561536/android_virtual_cam#61]
试了几个手机激活以后都卡在开机界面，不能开机
红米5 plus
华为p10
oppo r9s

**Comment by w2016561536** [comment]
系统相机基本都会出问题
不要开启全局模式，使用作用域限制模块。

而且手机为啥无法激活？

**Comment by w2016561536** [comment]
已经找到问题所在，可以先使用3.4版本，将在之后发布新版本

**Comment by netstu** [comment]
谢谢，改用3.4可以了
