### ISSUE TITLE
Triggering read

### ISSUE THREAD

**Issue by kababoom** [w2016561536/android_virtual_cam#62]
Thank you for this great module.......

I got a qr-reading app, replacing input works and displays correct image but it does not 'trigger' the app to decode the qr.

Any idea how to activate the triggering?

感谢你的代码库
我现在有个问题如下：我有一个gr-reading app, 二维码可以不用扫描 然后直接播放一个二维码的视频来代替， 这个正常运行，但它然后好像就不行激活app来解析二维码。简单来说，它识别到了二维码，但是不知道怎么去处理二维码。

请问怎么样才能让app来解析和处理二维码？提前感谢

**Comment by w2016561536** [comment]
能否发一下应用程序?

**Comment by kababoom** [comment]
Not native but close to it..  My native Chinese colleague translated it but I don't think I did explain him the purpose properly :-)

Can I send you the app in a pm?

**Comment by w2016561536** [comment]
Sure 
Play store link, google drive,one drive.All of them are ok

**Comment by kababoom** [comment]
Working when using correct input video format...
