### ISSUE TITLE
视频放在app私有目录无法识别，但放在系统DCIM可以识别

### ISSUE THREAD

**Issue by chinasoul** [w2016561536/android_virtual_cam#63]
拍摄了段1920*1080视频，命名virtual.mp4放入DCIM/Camera1/可以。
放入私有路径Android\data\com.eg.android.AlipayGphone\files\Camera1，若干次toast提示不存在替换视频 ，最后一个toast提示发现预览xxx之类的

**Comment by w2016561536** [comment]
打开应用时没有提示未获取权限就不需要放在私有目录

**Comment by w2016561536** [comment]
不存在替换视频，会告诉你应该放在哪个目录

**Comment by chinasoul** [comment]
so this should be expected, close.
