### ISSUE TITLE
app内点击拍照无法做到截取视频中的一帧

### ISSUE THREAD

**Issue by chinasoul** [w2016561536/android_virtual_cam#64]
例子（类似app要求通过相机实时拍一张身份证上传）：app已经读取到了virtual.mp4，然后点击拍照，期望是app获取到点击拍照那一刻视频中的那一帧，结果是拍到的是真实照片。然后我按照guide放入一张1000.bmp，重复上述步骤，结果是app获取到了1000.bmp（并且是水平翻转的）
期望：用户能将virtual.mp4中的任意一帧作为拍照结果让app识别。

**Comment by w2016561536** [comment]
1000.bmp自行旋转翻转
