### ISSUE TITLE
视频无声音

### ISSUE THREAD

**Issue by lbr188** [w2016561536/android_virtual_cam#68]
对方接视频听不到视频文件播放的声音怎么解决？在自述文件看到如果需要播放视频的声音，则需要在Camera1目录下创建no-silent.jpg文件。请问no-silent.jpg文件怎么创建，麻烦大师指点，谢谢！
另外有没有软件直接在软件直接替换视频，这样比较方便。

**Comment by w2016561536** [comment]
就是创建一个空文件啊。
