### ISSUE TITLE
[Bug]没有申请读写存储权限

### ISSUE THREAD

**Issue by Kia678** [w2016561536/android_virtual_cam#75]
![IMG_20220112_195457](https://user-images.githubusercontent.com/85081567/149135947-9a7f6614-d25f-4c60-8aa2-68adb59a5114.jpg)

VCam的权限截图如上，VCam一直在toast提示没有读写存储权限，但是却没有申请读写存储权限，也没有添加申请读写存储的权限功能

设备: MIUI 12 based on Android 10

**Comment by w2016561536** [comment]
是目标应用
不是VCam

请仔细阅读Readme
