### ISSUE TITLE
三方APP相机物体识别问题

### ISSUE THREAD

**Issue by GLORIA925** [w2016561536/android_virtual_cam#79]
在钉钉打卡开启了微笑打卡后，使用VCAM替代视频，钉钉一直无法识别到人脸。切换为真实视像头画面能够很灵敏的捕捉到人脸并进行识别。

**Comment by w2016561536** [comment]
也请不要用于此类用途

**Comment by GLORIA925** [comment]
> 需要匹配分辨率 前置摄像头需要左旋90

在开启微笑打卡界面没有弹出Toast消息显示分辨率，签到界面显示宽1920/高1080，同一手机使用谷歌相机前置摄像有拍摄相同分辨率视频，替换视频显示正常的，这样还需要左旋90°适配分辨率吗？

**Comment by w2016561536** [comment]
既然不行的话，那为啥不尝试一下呢？？

**Comment by GLORIA925** [comment]
> 

已经找到其他方式激活识别了，谢谢大佬的耐心解答，非常感谢您的软件哈！

**Comment by Mrkhalilimitik** [comment]
> 

@GLORIA925 Hey can you help me in that?
