### ISSUE TITLE
Cam video is streched

### ISSUE THREAD

**Issue by robkor26** [w2016561536/android_virtual_cam#84]
Could anyone try to help me fix the problem with my cam video? 
The video image is always stretched when using camera no matter what resolution I download video.
I can't see any toast I can change resolution.  Has anyone got idea what I do wrong? 
In video player the video plays well however when using vcam it is always stretched. My device is xiaomi 11. 
I appreciate for any help. Thank you

**Comment by w2016561536** [comment]
No toast messages?
Try to change the resolution to your screen’s resolution

**Comment by w2016561536** [comment]
Sometimes you need a rotation

**Comment by w2016561536** [comment]
Sorry, you need to know that the raw image would be processed by app, such as rotation. Because system provides an image without rotation regardless of your phone's direction. I can't hook every app's process method one by one.

**Comment by RADIDSAS** [comment]
hello when i put video in folder video display destroyed and target app still pending for accept the video what is the problem
