### ISSUE TITLE
兼容性不行

### ISSUE THREAD

**Issue by TangJhan** [w2016561536/android_virtual_cam#86]
xposed来做这个不够用，兼容性差的很，在咸鱼上一堆工作室拿来套钱，哄一些小白，真正的摄像头劫持不重新编译源码等于玩具，fork，和start这么多人，估计都是搞黑灰的

**Comment by w2016561536** [comment]
如果你是通过购买的渠道获得该软件，而且售卖者并未告知能通过免费的渠道获取，请退款+投诉。
至于破解人脸识别的用途，该工具无法中途替换视频，大部分的人脸识别会直接露馅。
的确，通过修改安卓源代码来实现能实现更好的效果，但是通用性就会大打折扣。
