### ISSUE TITLE
无法使用扫脸功能

### ISSUE THREAD

**Issue by ZRbyGit** [w2016561536/android_virtual_cam#89]
用虚拟摄像头扫脸的时候就会提示检查不到人脸（合法用途
![Uploading mmexport1646541510291~2.jpg…]()
）

**Comment by w2016561536** [comment]
请查看[常见问题](https://github.com/w2016561536/android_virtual_cam#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)自行解决
