### ISSUE TITLE
抖音点击录像无法从头开始播放视频

### ISSUE THREAD

**Issue by ptltc** [w2016561536/android_virtual_cam#91]
抖音录像时视频无法从头开始播放，只会从播放中途开始录像，如果想要在点击录像时自动从头开始播放视频需要怎么做？能否在打开抖音拍摄时视频是停止状态，不要是播放状态，等点击拍摄时开始播放视频？

**Comment by w2016561536** [comment]
问题是我不知道应用程序什么时候开始录制

可能需要你卡准时机

**Comment by ptltc** [comment]
能不能加一个可以设置视频是停止状态或自动播放状态，可以开关，这样的话如果需要视频从头开始拍摄，就把视频设置为停播状态，应用打开时视频是停止的，点击开始拍摄的时候同时触发视频播放，这样就能从头开始拍摄视频，如果有需要拍摄视频中间的某段内容的时候就设置为视频自动播放，应用拍摄就从中途开始。

**Comment by wangimyayo** [comment]
> 问题是我不知道应用程序什么时候开始录制
> 
> 可能需要你卡准时机

监听开始按键

**Comment by ptltc** [comment]
能否监听拍摄的按键来触发视频开始播放录制？
