### ISSUE TITLE
退出宿主app时mock的视频声音还在播放

### ISSUE THREAD

**Issue by yamioo** [w2016561536/android_virtual_cam#95]
你好，在android10系统上，当退出快手应用, mock视频的声音还在播放，期待您的回复

**Comment by w2016561536** [comment]
这个自动关闭声音的功能被弃用了（有bug）
如果实在要用，需要退回3.2版本https://gitee.com/w2016561536/android_virtual_cam/blob/6fc4920fbf1916ca618b9360d466e87ebae6cf38/app/release/app-release.apk
