### ISSUE TITLE
可否增加保存真实摄像头数据成视频文件

### ISSUE THREAD

**Issue by asasqwwq** [w2016561536/android_virtual_cam#96]
可否增加保存真实摄像头数据成视频文件，其他APP使用摄像头的同时

**Comment by w2016561536** [comment]
这个东西的难点在于API复杂
安卓相机的API有好几个，而且每个处理方式不太相同
有时候会出现应用程序重复调用的问题
其次，这个功能并不是此项目的重点

**Comment by taquila133** [comment]
Sent from Android device2022年3月19日 下午6:59，w2016561536 ***@***.***>寫道：

这个东西的难点在于API复杂

安卓相机的API有好几个，而且每个处理方式不太相同

有时候会出现应用程序重复调用的问题

其次，这个功能并不是此项目的重点

**Comment by taquila133** [comment]
Sent from Android device2022年3月19日 下午9:50，亞虎 ***@***.***>寫道：Sent from Android device2022年3月19日 下午6:59，w2016561536 ***@***.***>寫道：

这个东西的难点在于API复杂

安卓相机的API有好几个，而且每个处理方式不太相同

有时候会出现应用程序重复调用的问题

其次，这个功能并不是此项目的重点
