### ISSUE TITLE
如何解决安卓应用双开作用后找不到替换视频路径

### ISSUE THREAD

**Issue by Nicktianyu** [w2016561536/android_virtual_cam#97]
当需要作用的APP双开的时候,也需要把此模块双开,可是经过分身出来的APP要用此模块的分身拍摄的时候,就会显示不存在替换视频 当前路径.....如何解决?

**Comment by w2016561536** [comment]
模块会告诉你路径在哪，根据弹出的消息放

在 2022年3月18日，下午9:07，Nicktianyu ***@***.***> 写道：

当需要作用的APP双开的时候,也需要把此模块双开,可是经过分身出来的APP要用此模块的分身拍摄的时候,就会显示不存在替换视频 当前路径.....如何解决?

**Comment by Nicktianyu** [comment]
好,那就是每次都需要把视频放在提示的路径里 能否像原App那样自动存放 或者跟原App使用同一个路径呢?

**Comment by w2016561536** [comment]
原app也需要手动搬运啊
安卓不允许夸用户读取

在 2022年3月18日，下午9:24，Nicktianyu ***@***.***> 写道：

好,那就是每次都需要把视频放在提示的路径里 能否像原App那样自动存放 或者跟原App使用同一个路径呢?

**Comment by Nicktianyu** [comment]
我原APP不需要搬 下载后直接用视频旋转配合内录小工具直接就可以虚拟内录了
