### ISSUE TITLE
雷电模拟器下 出现未授予读取本地目录权限，请检查权限

### ISSUE THREAD

**Issue by GuokeTnT** [w2016561536/android_virtual_cam#98]
一直气泡提示：{应用包名}未授予读取本地目录权限，请检查权限 Camera1目前重定向为/内部存储/Android/data/{应用包名}/files/Camera1/                           求大佬解答 我一直弄不明白! 感谢各位！

**Comment by w2016561536** [comment]
把视频复制到这个地方

**Comment by kenlam5551** [comment]
我也是這樣 一按拍照就彈這個氣泡了

**Comment by matthewkram419** [comment]
> И я тоже. Я щелкнул этот пузырь, как только нажал, чтобы сделать снимок

兄弟，告诉我为什么它不会在大多数应用程序中替换照片？ 视频替换，但照片没有
