### ISSUE TITLE
放置virtual.mp4显示本机摄像头

### ISSUE THREAD

**Issue by zhihuiyuze** [w2016561536/android_virtual_cam#99]
您好，
    我安卓了以后在`/sdcard/DCIM/Camera1`放了个virtual.mp4，但是打开摄像头还是本机摄像头。我又看教程然后又创建了1000.bmp，但是依旧为本机摄像头。我已确定模块已经启动，但我区看日志并没有找到android_virtual_cam相关内容。
以下是日志文件
[EdXposed_Verbose_20220326_164958.txt](https://github.com/w2016561536/android_virtual_cam/files/8355030/EdXposed_Verbose_20220326_164958.txt)

![image](https://user-images.githubusercontent.com/38281461/160232321-6341d176-b2dc-4d29-8a53-ad919bd3cf5c.png)

**Comment by joylous** [comment]
你选中相机app了吗

**Comment by zhihuiyuze** [comment]
请问如何选择？

**Comment by weisuosheng** [comment]
我也遇到此问题了，很奇怪，之前还能替换视频，突然不能替换了，方法步骤完全按照要求来的

**Comment by zhihuiyuze** [comment]
您好，感谢各位的回复。

我已经解决了问题，目前更换了手机还没有在现在的手机上测试转发功能。

因为APP拍照的时候不光需要mp4,当我按下拍照按钮的时候实际上是读取目录下的1000.bmp文件

谢谢

**Comment by kenlam5551** [comment]
請問大神怎樣可以在APP內拍下指定照片，我放了1000.bmp都不行，但放virtual.mp4 可以讀出影片，但一按拍照就失敗了
